# generated by datamodel-codegen:
#   filename:  public_schema.yaml
#   timestamp: 2024-03-27T08:00:12+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Consultation(BaseModel):
    name: Optional[str] = Field(
        None,
        description='The name of the consultation',
        example='Consultation on Kit Kats',
    )


class Section(BaseModel):
    name: Optional[str] = Field(
        None,
        description='The name of the section',
        example='When to enforce a Kit Kat ban',
    )


class Question(BaseModel):
    text: Optional[str] = Field(
        None,
        description='The question text',
        example='Should Kit Kats be banned on Tuesdays',
    )
    has_free_text: Optional[bool] = Field(
        None, description='Does this question have a free text component?'
    )
    multiple_choice_options: Optional[List[str]] = Field(
        None,
        description='The options for the multiple choice part of this question, if it has a multiple choice component',
    )


class Answer(BaseModel):
    multiple_choice: Optional[List[str]] = Field(
        None,
        description='Responses to the multiple choice part of the question, if any',
    )
    free_text: Optional[str] = Field(
        None, description='The answer to the free text part of the question, if any'
    )


class ConsultationResponse(BaseModel):
    pass
