# generated by datamodel-codegen:
#   filename:  public_schema.yaml
#   timestamp: 2024-03-27T09:03:22+00:00

from __future__ import annotations

from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class Question(BaseModel):
    id: Optional[UUID] = None
    text: Optional[str] = Field(
        None,
        description='The question text',
        example='Should Kit Kats be banned on Tuesdays',
    )
    has_free_text: Optional[bool] = Field(
        None, description='Does this question have a free text component?'
    )
    multiple_choice_options: Optional[List[str]] = Field(
        None,
        description='The options for the multiple choice part of this question, if it has a multiple choice component',
    )


class Answer(BaseModel):
    multiple_choice: Optional[List[str]] = Field(
        None,
        description='Responses to the multiple choice part of the question, if any',
    )
    free_text: Optional[str] = Field(
        None, description='The answer to the free text part of the question, if any'
    )


class ConsultationResponse(BaseModel):
    answers: Optional[List[Answer]] = None


class Section(BaseModel):
    name: Optional[str] = Field(
        None,
        description='The name of the section',
        example='When to enforce a Kit Kat ban',
    )
    questions: Optional[List[Question]] = None


class Consultation(BaseModel):
    name: Optional[str] = Field(
        None,
        description='The name of the consultation',
        example='Consultation on Kit Kats',
    )
    sections: Optional[List[Section]] = None
